[boris]
  version = 1

[build.dist-7-10-build]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-build"]
    ]

[build.dist-7-10-cli]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-cli"]
    ]

[build.dist-7-10-config-toml]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-config-toml"]
    ]

[build.dist-7-10-machinator]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-machinator"]
    ]

[build.dist-7-10-http]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-http"]
    ]

[build.dist-7-10-process]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-process"]
    ]

[build.dist-7-10-projector]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-projector"]
    ]

[build.dist-7-10-sass]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-sass"]
    ]

[build.dist-7-10-site]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-site"]
    ]

[build.dist-7-10-wai-assets]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-wai-assets"]
    ]

[build.branches-7-10-build]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-build"]
    ]

[build.branches-7-10-cli]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-cli"]
    ]

[build.branches-7-10-config-toml]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-config-toml"]
    ]

[build.branches-7-10-machinator]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-machinator"]
    ]

[build.branches-7-10-http]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-http"]
    ]

[build.branches-7-10-process]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-process"]
    ]

[build.branches-7-10-projector]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-projector"]
    ]

[build.branches-7-10-sass]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-sass"]
    ]

[build.branches-7-10-site]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-site"]
    ]

[build.branches-7-10-wai-assets]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-wai-assets"]
    ]

[build.dist-validate]
  command = [["validate-respect"]]

[build.all-rebased]
  command = [["rebased"]]

[build.all-submodules]
  command = [["dangling-refs"]]
